# Reducing angular derivative
gains:
  pos: {x: 2.2, y: 2.2, z: 8.0} 
  vel: {x: 1.5, y: 1.5, z: 3.0}  
  rot: {x: 1.5, y: 1.5, z: 0.12}
  ang: {x: 0.13, y: 0.13, z: 0.012}
  ki:  {x: 0.001, y: 0.001, z: 0.0}
corrections:
  kf: 0.000000006
  r: 0.0
  p: 0.0

