# Reducing angular derivative
gains:
  #pos: {x: 1.4, y: 1.4, z: 2.2}
  #vel: {x: 0.4, y: 0.4, z: 0.5}
  pos: {x: 1.8, y: 1.8, z: 3.0}
  vel: {x: 0.6, y: 0.6, z: 1.7}
  rot: {x: 0.34, y: 0.34, z: 0.28}
  ang: {x: 0.03, y: 0.03, z: 0.02}
  ki:  {x: 0.00, y: 0.001, z: 0.008}
corrections:
  kf: 0.0
  r: 0.0
  p: 0.0

