sync_topics: ['/nanokontrol2','/vicon/TransportationBar/odom', /QuadrotorQc18/quadrotor_ukf/control_odom, /QuadrotorQc18/MVSampleVISLAMEagle/vio_pose, /QuadrotorQc18/vio_pose_graph, /QuadrotorQc18/wm, /QuadrotorQc18/so3_cmd, /QuadrotorQc18/position_cmd, /QuadrotorQc18/des_odom, /QuadrotorQc19/quadrotor_ukf/control_odom, /QuadrotorQc19/vio_pose_graph, /QuadrotorQc19/wm, /QuadrotorQc19/so3_cmd, /QuadrotorQc19/position_cmd, /QuadrotorQc19/des_odom]
ignore_nodes: ['/rviz']
ignore_services: ['/*']

