distribution:
  posx: {x1: 0.0, x2: 0.0, x3: 0.0, x4: 0.0}
  posy: {y1: 0.185, y2: -0.185, y3: 0.0, y4: 0.0}
  posz: {z1: 0.0, z2: 0.0, z3: 0.0, z4: 0.0}
  pospsi: {psi1: 0.0, psi2: 0.0, psi3: 0.0, psi4: 0.0}
num_vehicles: 2
secondaty_task: true
optimize: true
